[simulation]
diffusion_type_ = "RK"

[visualization]
export = true
export_interval = 1

    [[visualize_sim_object]]
    name = "Cell"
    additional_data_members = [ "diameter_" ]

    [[visualize_diffusion]]
    name = "SARS-CoV-2"
    gradient = false

    [[visualize_diffusion]]
    name = "SARS-CoV-2-droplets"
    gradient = false
